import type { LangId } from "@/i18n";

// Varga (divisional chart) name + subtitle localization.
//
// Everything here is written for a native reader of each language - native
// script throughout, no transliteration left in the wrong script and no Latin
// crutches inside CJK/RTL text.
//
// The chart *name* (Rashi, Hora, Navamsa, ...) is a Sanskrit proper noun
// rendered in each language's own script (Devanagari for hi/ne, Tamil, Bengali,
// Chinese, Japanese kana, Cyrillic, Arabic, Perso-Arabic, Hebrew), mirroring how
// src/i18n/astro.ts renders planet/sign/nakshatra names. Latin-script European
// locales (es, de, pt, fr) keep the Latin Sanskrit name, matching the planet and
// sign names shown next to them.
//
// The *subtitle* is the meaning of the chart (what life area it governs) and is
// translated into each language.
//
// Lookup falls back to the English string the backend already returns when a
// locale or division has no entry, so the UI never shows an empty label.

type VargaDict = {
  names: Record<number, string>;
  subs: Record<number, string>;
};

// English names mirror backend VARGA_NAMES; used as the Latin fallback and for
// the Latin-script European locales.
const NAMES_EN: Record<number, string> = {
  1: "Rashi",
  2: "Hora",
  3: "Drekkana",
  4: "Chaturthamsa",
  7: "Saptamsa",
  9: "Navamsa",
  10: "Dashamsa",
  11: "Rudramsa",
  12: "Dvadashamsa",
  16: "Shodashamsa",
  20: "Vimshamsa",
  24: "Chaturvimshamsa",
  27: "Nakshatramsa (Bhamsa)",
  30: "Trimshamsa",
  40: "Khavedamsa",
  45: "Akshavedamsa",
  60: "Shashtyamsa",
};

const HI: VargaDict = {
  names: {
    1: "राशि",
    2: "होरा",
    3: "द्रेक्काण",
    4: "चतुर्थांश",
    7: "सप्तांश",
    9: "नवांश",
    10: "दशांश",
    11: "रुद्रांश",
    12: "द्वादशांश",
    16: "षोडशांश",
    20: "विंशांश",
    24: "चतुर्विंशांश",
    27: "नक्षत्रांश (भांश)",
    30: "त्रिंशांश",
    40: "खवेदांश",
    45: "अक्षवेदांश",
    60: "षष्ट्यंश",
  },
  subs: {
    1: "देह · शरीर",
    2: "धन",
    3: "भ्राता · पराक्रम",
    4: "सुख · गृह",
    7: "संतान",
    9: "भाग्य · दाम्पत्य",
    10: "कर्म · आजीविका",
    11: "लाभ · आय",
    12: "माता-पिता",
    16: "वाहन · सुख",
    20: "आध्यात्मिक प्रगति",
    24: "विद्या · शिक्षा",
    27: "बल-निर्बल",
    30: "अनिष्ट",
    40: "मातृ-वंश",
    45: "पितृ-वंश",
    60: "पूर्व-जन्म कर्म",
  },
};

const TA: VargaDict = {
  names: {
    1: "ராசி",
    2: "ஹோரை",
    3: "திரேக்காணம்",
    4: "சதுர்த்தாம்சம்",
    7: "சப்தாம்சம்",
    9: "நவாம்சம்",
    10: "தசாம்சம்",
    11: "ருத்ராம்சம்",
    12: "துவாதசாம்சம்",
    16: "ஷோடசாம்சம்",
    20: "விம்சாம்சம்",
    24: "சதுர்விம்சாம்சம்",
    27: "நக்ஷத்ராம்சம் (பாம்சம்)",
    30: "திரிம்சாம்சம்",
    40: "கவேதாம்சம்",
    45: "அக்ஷவேதாம்சம்",
    60: "ஷஷ்டியம்சம்",
  },
  subs: {
    1: "உடல் · சுயம்",
    2: "செல்வம்",
    3: "உடன்பிறந்தோர் · தைரியம்",
    4: "அதிர்ஷ்டம் · வீடு",
    7: "குழந்தைகள்",
    9: "வாழ்க்கைத்துணை · தர்மம்",
    10: "தொழில் · சாதனை",
    11: "ஆதாயம் · வருமானம்",
    12: "பெற்றோர்",
    16: "வாகனம் · சுகம்",
    20: "ஆன்மிக முன்னேற்றம்",
    24: "கல்வி · அறிவு",
    27: "பலம் · பலவீனம்",
    30: "துன்பங்கள்",
    40: "தாய்வழி மரபு",
    45: "தந்தைவழி மரபு",
    60: "முற்பிறவி வினை",
  },
};

const BN: VargaDict = {
  names: {
    1: "রাশি",
    2: "হোরা",
    3: "দ্রেক্কাণ",
    4: "চতুর্থাংশ",
    7: "সপ্তাংশ",
    9: "নবাংশ",
    10: "দশাংশ",
    11: "রুদ্রাংশ",
    12: "দ্বাদশাংশ",
    16: "ষোড়শাংশ",
    20: "বিংশাংশ",
    24: "চতুর্বিংশাংশ",
    27: "নক্ষত্রাংশ (ভাংশ)",
    30: "ত্রিংশাংশ",
    40: "খবেদাংশ",
    45: "অক্ষবেদাংশ",
    60: "ষষ্ট্যংশ",
  },
  subs: {
    1: "দেহ · শরীর",
    2: "ধন",
    3: "ভাইবোন · সাহস",
    4: "সৌভাগ্য · গৃহ",
    7: "সন্তান",
    9: "দাম্পত্য · ধর্ম",
    10: "কর্ম · সাফল্য",
    11: "লাভ · আয়",
    12: "পিতা-মাতা",
    16: "যানবাহন · সুখ",
    20: "আধ্যাত্মিক উন্নতি",
    24: "বিদ্যা · শিক্ষা",
    27: "বল-দুর্বলতা",
    30: "দুর্ভাগ্য",
    40: "মাতৃকুল",
    45: "পিতৃকুল",
    60: "পূর্বজন্মের কর্ম",
  },
};

const NE: VargaDict = {
  names: { ...HI.names },
  subs: {
    1: "देह · शरीर",
    2: "धन",
    3: "दाजुभाइ · पराक्रम",
    4: "भाग्य · घर",
    7: "सन्तान",
    9: "दाम्पत्य · धर्म",
    10: "करियर · उपलब्धि",
    11: "लाभ · आय",
    12: "आमाबुबा",
    16: "सवारी · सुख",
    20: "आध्यात्मिक प्रगति",
    24: "विद्या · शिक्षा",
    27: "बल-कमजोरी",
    30: "दुर्भाग्य",
    40: "मातृ-वंश",
    45: "पितृ-वंश",
    60: "पूर्वजन्मको कर्म",
  },
};

const ZH: VargaDict = {
  names: {
    1: "罗西盘",
    2: "霍拉盘",
    3: "德雷卡纳盘",
    4: "四分盘",
    7: "七分盘",
    9: "九分盘",
    10: "十分盘",
    11: "十一分盘",
    12: "十二分盘",
    16: "十六分盘",
    20: "二十分盘",
    24: "二十四分盘",
    27: "纳克沙特拉盘 (二十七分盘)",
    30: "三十分盘",
    40: "四十分盘",
    45: "四十五分盘",
    60: "六十分盘",
  },
  subs: {
    1: "身体 · 自我",
    2: "财富",
    3: "兄弟姐妹 · 勇气",
    4: "福运 · 家宅",
    7: "子女",
    9: "配偶 · 法",
    10: "事业 · 成就",
    11: "收益 · 收入",
    12: "父母",
    16: "车辆 · 享受",
    20: "灵性进展",
    24: "教育 · 学识",
    27: "强弱",
    30: "厄运",
    40: "母系传承",
    45: "父系传承",
    60: "前世业力",
  },
};

const JA: VargaDict = {
  names: {
    1: "ラーシ",
    2: "ホーラ",
    3: "ドレッカーナ",
    4: "チャトゥルタムシャ",
    7: "サプタムシャ",
    9: "ナヴァムシャ",
    10: "ダシャムシャ",
    11: "ルドラムシャ",
    12: "ドヴァダシャムシャ",
    16: "ショーダシャムシャ",
    20: "ヴィムシャムシャ",
    24: "チャトゥルヴィムシャムシャ",
    27: "ナクシャトラムシャ (バームシャ)",
    30: "トリムシャムシャ",
    40: "カヴェーダムシャ",
    45: "アクシャヴェーダムシャ",
    60: "シャシュティアムシャ",
  },
  subs: {
    1: "身体 · 自己",
    2: "財産",
    3: "兄弟姉妹 · 勇気",
    4: "幸運 · 家庭",
    7: "子供",
    9: "配偶者 · ダルマ",
    10: "仕事 · 達成",
    11: "利得 · 収入",
    12: "両親",
    16: "乗り物 · 快適",
    20: "霊的進歩",
    24: "教育 · 学問",
    27: "強さと弱さ",
    30: "災い",
    40: "母方の系譜",
    45: "父方の系譜",
    60: "前世のカルマ",
  },
};

const ES: VargaDict = {
  names: { ...NAMES_EN },
  subs: {
    1: "Cuerpo · Ser fisico",
    2: "Riqueza",
    3: "Hermanos · Valor",
    4: "Fortuna · Hogar",
    7: "Hijos",
    9: "Conyuge · Dharma",
    10: "Carrera · Logros",
    11: "Ganancias · Ingresos",
    12: "Padres",
    16: "Vehiculos · Comodidades",
    20: "Progreso espiritual",
    24: "Educacion · Aprendizaje",
    27: "Fortalezas · Debilidades",
    30: "Infortunios",
    40: "Linaje materno",
    45: "Linaje paterno",
    60: "Karma de vidas pasadas",
  },
};

const DE: VargaDict = {
  names: { ...NAMES_EN },
  subs: {
    1: "Korper · Selbst",
    2: "Reichtum",
    3: "Geschwister · Mut",
    4: "Gluck · Heim",
    7: "Kinder",
    9: "Partner · Dharma",
    10: "Karriere · Erfolg",
    11: "Gewinne · Einkommen",
    12: "Eltern",
    16: "Fahrzeuge · Annehmlichkeiten",
    20: "Spiritueller Fortschritt",
    24: "Bildung · Lernen",
    27: "Starken · Schwachen",
    30: "Ungluck",
    40: "Mutterliche Abstammung",
    45: "Vaterliche Abstammung",
    60: "Karma fruherer Leben",
  },
};

const PT: VargaDict = {
  names: { ...NAMES_EN },
  subs: {
    1: "Corpo · Ser fisico",
    2: "Riqueza",
    3: "Irmaos · Coragem",
    4: "Fortuna · Lar",
    7: "Filhos",
    9: "Conjuge · Dharma",
    10: "Carreira · Realizacao",
    11: "Ganhos · Renda",
    12: "Pais",
    16: "Veiculos · Confortos",
    20: "Progresso espiritual",
    24: "Educacao · Aprendizado",
    27: "Forcas · Fraquezas",
    30: "Infortunios",
    40: "Linhagem materna",
    45: "Linhagem paterna",
    60: "Carma de vidas passadas",
  },
};

const FR: VargaDict = {
  names: { ...NAMES_EN },
  subs: {
    1: "Corps · Soi physique",
    2: "Richesse",
    3: "Freres et soeurs · Courage",
    4: "Fortune · Foyer",
    7: "Enfants",
    9: "Conjoint · Dharma",
    10: "Carriere · Reussite",
    11: "Gains · Revenus",
    12: "Parents",
    16: "Vehicules · Conforts",
    20: "Progres spirituel",
    24: "Education · Savoir",
    27: "Forces · Faiblesses",
    30: "Malheurs",
    40: "Lignee maternelle",
    45: "Lignee paternelle",
    60: "Karma des vies passees",
  },
};

const RU: VargaDict = {
  names: {
    1: "Раши",
    2: "Хора",
    3: "Дреккана",
    4: "Чатуртхамша",
    7: "Саптамша",
    9: "Навамша",
    10: "Дашамша",
    11: "Рудрамша",
    12: "Двадашамша",
    16: "Шодашамша",
    20: "Вимшамша",
    24: "Чатурвимшамша",
    27: "Накшатрамша (Бхамша)",
    30: "Тримшамша",
    40: "Кхаведамша",
    45: "Акшаведамша",
    60: "Шаштьямша",
  },
  subs: {
    1: "Тело · Личность",
    2: "Богатство",
    3: "Братья и сестры · Смелость",
    4: "Удача · Дом",
    7: "Дети",
    9: "Супруг · Дхарма",
    10: "Карьера · Достижения",
    11: "Прибыль · Доход",
    12: "Родители",
    16: "Транспорт · Комфорт",
    20: "Духовный прогресс",
    24: "Образование · Знания",
    27: "Сильные и слабые стороны",
    30: "Несчастья",
    40: "Материнская линия",
    45: "Отцовская линия",
    60: "Карма прошлых жизней",
  },
};

const AR: VargaDict = {
  names: {
    1: "راشي",
    2: "هورا",
    3: "دريكانا",
    4: "تشاتورثامسا",
    7: "سابتامسا",
    9: "نافامسا",
    10: "داشامسا",
    11: "رودرامسا",
    12: "دفاداشامسا",
    16: "شودامسا",
    20: "فيمشامسا",
    24: "تشاتورفيمشامسا",
    27: "ناكشاترامسا (بهامسا)",
    30: "تريمشامسا",
    40: "خافيدامسا",
    45: "أكشافيدامسا",
    60: "شاشتيامسا",
  },
  subs: {
    1: "الجسد · الذات",
    2: "الثروة",
    3: "الإخوة · الشجاعة",
    4: "الحظ · المنزل",
    7: "الأبناء",
    9: "الزوج · الدارما",
    10: "المهنة · الإنجاز",
    11: "المكاسب · الدخل",
    12: "الوالدان",
    16: "المركبات · وسائل الراحة",
    20: "التقدم الروحي",
    24: "التعليم · المعرفة",
    27: "نقاط القوة والضعف",
    30: "المصائب",
    40: "النسب الأمومي",
    45: "النسب الأبوي",
    60: "كارما الحيوات السابقة",
  },
};

const FA: VargaDict = {
  names: {
    1: "راشی",
    2: "هورا",
    3: "دریکانا",
    4: "چهارتهامسا",
    7: "هفتمسا",
    9: "ناوامسا",
    10: "داشامسا",
    11: "رودرامسا",
    12: "دوازدهمسا",
    16: "شودامسا",
    20: "ویمشامسا",
    24: "چهارویمشامسا",
    27: "ناکشاترامسا (بهامسا)",
    30: "تریمشامسا",
    40: "خاودامسا",
    45: "اکشاودامسا",
    60: "شاشتیامسا",
  },
  subs: {
    1: "بدن · خویشتن",
    2: "ثروت",
    3: "خواهر و برادر · شجاعت",
    4: "بخت · خانه",
    7: "فرزندان",
    9: "همسر · دارما",
    10: "شغل · موفقیت",
    11: "سود · درآمد",
    12: "والدین",
    16: "خودرو · آسایش",
    20: "پیشرفت معنوی",
    24: "آموزش · دانش",
    27: "نقاط قوت و ضعف",
    30: "بدبختی‌ها",
    40: "تبار مادری",
    45: "تبار پدری",
    60: "کارمای زندگی‌های پیشین",
  },
};

const HE: VargaDict = {
  names: {
    1: "ראשי",
    2: "הורה",
    3: "דרקאנה",
    4: "צ'תורתמסה",
    7: "ספטמסה",
    9: "נבמסה",
    10: "דשמסה",
    11: "רודרמסה",
    12: "דוודשמסה",
    16: "שודשמסה",
    20: "וימשמסה",
    24: "צ'תורוימשמסה",
    27: "נקשטרמסה (בהמסה)",
    30: "טרימשמסה",
    40: "חבדמסה",
    45: "אקשבדמסה",
    60: "ששטימסה",
  },
  subs: {
    1: "גוף · עצמי",
    2: "עושר",
    3: "אחים · אומץ",
    4: "מזל · בית",
    7: "ילדים",
    9: "בן/בת זוג · דהרמה",
    10: "קריירה · הישגים",
    11: "רווחים · הכנסה",
    12: "הורים",
    16: "כלי רכב · נוחות",
    20: "התקדמות רוחנית",
    24: "השכלה · לימוד",
    27: "חוזקות · חולשות",
    30: "מצוקות",
    40: "שושלת אם",
    45: "שושלת אב",
    60: "קארמה מגלגולים קודמים",
  },
};

const DICTS: Record<string, VargaDict> = {
  hi: HI,
  ne: NE,
  ta: TA,
  bn: BN,
  zh: ZH,
  ja: JA,
  es: ES,
  de: DE,
  pt: PT,
  fr: FR,
  ru: RU,
  ar: AR,
  fa: FA,
  he: HE,
};

export function vargaName(division: number, fallback: string, lang: LangId | string): string {
  return DICTS[lang]?.names[division] ?? fallback;
}

export function vargaSubtitle(
  division: number,
  fallback: string | undefined,
  lang: LangId | string,
): string | undefined {
  return DICTS[lang]?.subs[division] ?? fallback;
}
